# Generated by Django 3.1.4 on 2020-12-18 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quickstart', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='node',
            name='ip4',
            field=models.CharField(max_length=16),
        ),
    ]
